### ISSUE TITLE
Requesting support for Folia

### ISSUE THREAD

**Issue by Q2297045667** [Interguess/elevators#17]
Requesting support for Folia, https://github.com/PaperMC/Folia
I really like this plugin, so it's very important to me. Thank you

**Comment by JonasDevDE** [comment]
Hey! Thank you for opening this issue.

I will look into this right away.

**Comment by JonasDevDE** [comment]
@Q2297045667, could you please describe what exactly isn't working on Folia?

**Comment by Q2297045667** [comment]
> @Q2297045667, could you please describe what exactly isn't working on Folia?

I did not see folia-supported: true in the plugin.yml file

**Comment by JonasDevDE** [comment]
Did you tested if the plugin starts?

Don't think that this is required.

> > @Q2297045667, could you please describe what exactly isn't working on Folia?
> 
> I did not see folia-supported: true in the plugin.yml file

**Comment by Q2297045667** [comment]
> Did you tested if the plugin starts?
> 
> Don't think that this is required.
> 
> > > @Q2297045667, could you please describe what exactly isn't working on Folia?
> > 
> > 
> > I did not see folia-supported: true in the plugin.yml file

This is necessary, if Folia supported: true, Folia will not load the plugin

**Comment by Q2297045667** [comment]
> Did you tested if the plugin starts?
> 
> Don't think that this is required.
> 
> > > @Q2297045667, could you please describe what exactly isn't working on Folia?
> > 
> > 
> > I did not see folia-supported: true in the plugin.yml file
This is the error message when the plugin starts


[04:44:38] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins\Elevators-1.2.0.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins\Elevators-1.2.0.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at net.minecraft.server.Main.main(Main.java:131) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'IgElevators v1.2.0' as it is not marked as supporting Folia!
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.4.jar:git-Folia-"cd713b8"]
	... 20 more

**Comment by JonasDevDE** [comment]
Thanks! I will implement it now.

> > Did you tested if the plugin starts?
> > Don't think that this is required.
> > > > @Q2297045667, could you please describe what exactly isn't working on Folia?
> > > 
> > > 
> > > I did not see folia-supported: true in the plugin.yml file
> > > This is the error message when the plugin starts
> 
> [04:44:38] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins\Elevators-1.2.0.jar' failed to load! java.lang.RuntimeException: Directory 'plugins\Elevators-1.2.0.jar' failed to load! at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at net.minecraft.server.Main.main(Main.java:131) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?] at java.lang.Thread.run(Thread.java:1583) ~[?:?] Caused by: java.lang.RuntimeException: Could not load plugin 'IgElevators v1.2.0' as it is not marked as supporting Folia! at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] ... 20 more

**Comment by Q2297045667** [comment]
> Thanks! I will implement it now.
> 
> > > Did you tested if the plugin starts?
> > > Don't think that this is required.
> > > > > @Q2297045667, could you please describe what exactly isn't working on Folia?
> > > > 
> > > > 
> > > > I did not see folia-supported: true in the plugin.yml file
> > > > This is the error message when the plugin starts
> > 
> > 
> > [04:44:38] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins\Elevators-1.2.0.jar' failed to load! java.lang.RuntimeException: Directory 'plugins\Elevators-1.2.0.jar' failed to load! at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at net.minecraft.server.Main.main(Main.java:131) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?] at java.lang.Thread.run(Thread.java:1583) ~[?:?] Caused by: java.lang.RuntimeException: Could not load plugin 'IgElevators v1.2.0' as it is not marked as supporting Folia! at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.4.jar:git-Folia-"cd713b8"] ... 20 more

Thank you, your plugin is very interesting

**Comment by JonasDevDE** [comment]
https://modrinth.com/plugin/elevator/version/KYd5T4J3
